### ISSUE TITLE
error 8

### ISSUE THREAD

**Issue by BillPlayz** [cyberyen/cyberyen#13]
error -8: getblocktemplate must be called with the segwit & mweb rule sets (call with {"rules": ["mweb", "segwit"]})

**Comment by digirayc** [comment]
When serialising block, get response of getBlockTemplate, which includes additional object 'mweb'.
If mweb txs exist, append block with 1 followed by mweb object:
```
this.serializeBlock = function (header, coinbase){
       return Buffer.concat([
          header,
          util.varIntBuffer(this.rpcData.transactions.length + 1), coinbase, this.transactionData,
          Buffer.concat(rpData.mweb == null ? [] : [Buffer.from([1]), Buffer.from(rpcData.mweb, 'hex')]),
       ]);
}:
```
